train:
  data_path: data/train_lagged.csv
  predicting_weeks: 6
model:
  n_estimators: 1000
  learning_rate: 0.035
  max_depth: 12
  subsample: 0.8
  colsample_bytree: 0.7
  random_state: 42
  n_jobs: -1